### ISSUE TITLE
人物屬性大片紅字 [v0.5.4f-chs-1.0.0]

### ISSUE THREAD

**Issue by sapphiresu** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#10]
不好意思結果剛剛發現是我自己犯蠢🤣
剛剛自己解決這個問題了，不過我不太會用這個網站所以不確定該如何刪掉它

在這個場景點擊人物後會出現大片紅色錯誤，並且在場景裡點擊繼續的話會跳出錯誤警告，之前某些NPC也有出現紅色錯誤，不過不影響遊戲進行於是就沒管他了，結果現在被困在這裡
![Screenshot_20241017_154703_Course of Temptation](https://github.com/user-attachments/assets/445a852b-924b-4492-99e6-f7a5f00d70a2)
![Screenshot_20241017_154708_Course of Temptation](https://github.com/user-attachments/assets/9f11fd97-cf32-47f7-9630-9ba771d6c818)
![Screenshot_20241017_155057_Course of Temptation](https://github.com/user-attachments/assets/1b79bc4b-557f-49a6-8daa-e4d8531a3ab3)

**Comment by HCPTangHY** [comment]
这个是100的bug，在101已经修复，请注意检查版本
