### ISSUE TITLE
9033版战斗中切换姿势报错

### ISSUE THREAD

**Issue by HUNTERCAT** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#2]
oral、kneeling over、kneeling、riding face等后方带括号分上下或攻受的全部在切换时会弹窗报错，对手准备切换的场合显示姿势名也会报错，切换报错如图
![Screenshot_2024-09-04-23-52-20-358_com courseoftemptation app](https://github.com/user-attachments/assets/53c8aa27-41c1-4620-ba22-731fbe079c27)

**Comment by HCPTangHY** [comment]
新版已修复
