### ISSUE TITLE
V0.5.2f戰鬥畫面報錯

### ISSUE THREAD

**Issue by AeeFrost** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#3]
**描述**
請求不要更換動作或脫除衣服 、抵抗變換動作或脫除衣服、結束戰鬥都會跳出錯誤

**在反馈之前**
- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我在标题开头写明了当前使用的版本号，比如 [0.5.2d-chs-9033]

**截图**
请上传报错页面的截图，截图需要截完整页面，包括侧边栏打开的顶部版本号
![Screenshot_20240908-004749_Course_of_Temptation](https://github.com/user-attachments/assets/54f3d514-c908-4b63-976c-98521aafe9b3)

請求不要 、抵抗、結束都會跳出錯誤

**存档/存档码**
在上传存档或存档码方便汉化组复现

**Comment by HCPTangHY** [comment]
新版已修复

**Comment by AeeFrost** [comment]
謝謝~
