### ISSUE TITLE
ModI18N-0.5.3c-chs-9935.mod.zip漢化出現大量錯誤

### ISSUE THREAD

**Issue by AeeFrost** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#4]
**描述**
使用新版本的漢化出現大量錯誤

**在反馈之前**
- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我在标题开头写明了当前使用的版本号，比如 [0.5.2d-chs-9033]

**截图**
![Screenshot_20240908-220532_Course_of_Temptation](https://github.com/user-attachments/assets/31201d8c-79b0-4336-949e-4d8bedd695d8)
![Screenshot_20240908-221305_Course_of_Temptation](https://github.com/user-attachments/assets/076fa641-95d5-47eb-b5da-c5e47e14e560)
![Screenshot_20240908-221349_Course_of_Temptation](https://github.com/user-attachments/assets/23f8e8b2-e69c-4100-b265-4e2039e548cd)
![Screenshot_20240908-221426_Course_of_Temptation](https://github.com/user-attachments/assets/a9a52918-08f5-44c5-a3b4-a50d453d49c1)

**Comment by HCPTangHY** [comment]
新版已发，另外请更新游戏版本
