### ISSUE TITLE
卧室页面出现爆红

### ISSUE THREAD

**Issue by yawnzzn777** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#5]
版本[0.5.3c-chs-9081-2]
截图：
![Screenshot_2024-09-11-23-34-19-162_com courseoftemptation app](https://github.com/user-attachments/assets/661dfbcd-bfbc-4ed7-a2d9-0f940043bbc4)
存档码：N4IglgJiBcIMYHsCuAnAzgUwLQIGZYBcMBbABwIEMCwEA7EAGhDUqJlDFogwA8YAWJpgxRoABgB0AdikBWAGwBmMbICcARlX8N8ptwA2lGAG1Q1AvowwQAdQoBrDAFVSjEADcKKMBQBGltHYQYgpSNDAALytoY3kxMQZlMQBdJlIUDAxaRCRaIhRKAHNAmJBaBAx3LIJApnLfFBBUkAgKAE8YACYE4LoCAAsBJn7kRugpJmJOJDZxJjaMLy6xTSZCimIRdoEADjWNjAWl6HU0uFoD6wBpMAICNoACGTdSc7A4ewvN62ezwqzuGMQAQUBRaGh/lwMCgHrgSBRLC84BR/jB1HsQK8QgArBBjWhIfT6M45dAYErGEAAcSy0IRDwACmg2nARvoEIUOkwAJJ5FAIB4EAVMllsjlckAMkZCwqg0j9R7ctw02h0/QPADC/RIYBYKA6zVxvgpIAAykhiFMCA8ALJeRwENwARSQ73sYAwACFUP9Gs0sXRDl1tPx5IJMXA0KQMHAPSUQP0LWCkYcYwh2UD/EgrGd+hQwChEBnrGhcphrQhiA0cxG8wWWG1EbB2QhMA8wRAHgB3CjuCWvOsoSy0QoDaxTCBYXwUD4PYejwZnNDu7LpvHWXD5xpnThwfScKg0cEmEAAFQQjwAonlE+EKCw3AAZDBdzuXnj9MC+W5H3WOphUum3C0A8pojF20LQm4GoWmg+gzG4AAilYHnkSEoRceQPAAal+NYAGJ4j2KBQEwDL8kgb4fl+P50H+bing45KMoeWRwDWjEoP8/4gBqFAzDQSBoA876ft+1B0Q+TDYReGCoG4DLpm0Gx4sgtS2CMGRNEwu77hcEngrk7IfCIQTnleN5CT4D7QKAEAZAcoggtmAC+TDPq+InUeJv42XZDmbE5KCuQBQFZKB4GQWM/mLIFMDORgbm8bB8GOrZLQBaZ0AJUlAASW4PKe3iFL6QT2bFWU5UwhEoMRogxY58XBYlTDIVMmFpQ1cXZc1SVtah1q4b40RdZVvVkRRVFibRtD0el5WNT1IVnkxwkMqx2QjRlFVBctfECWpXnTQZc2jbtLUrVxGCddti1VSAMkLPJ82ZedSWKfoynEKpQlla9TXLTYmlbQt3U5UlrzLmARIlKAWpeLqIRovEPQ2ND+ikAgEFjOoKNMKJNEnWgxAwLI6idNJsmoIjXSdIoTCmrwSD0lc5RdpYECotA/CyBiiG6pwx1HjA8haK1GFguxyPxAzSC+FMaDhHQMCKJ0uggPlXACGI4YAPKgvoAhq9JKIHobJyqBiACCFzm6rPQMrSIKHlUXSqBMIC8kQRIxgQzPm7jMtmn7EBtJwhTSz0iGS+HkdkQq4TIgHeOStKHJygqccPZAGAClSGyxycKdWwUf7vFn+ckVkheB2IEORqwsMgCi0TosMGBgIU/RpaLFOYvBZCqoryzhsQQl7tE8jqOr1b3ta4RRFn0azcJC+tyn96r5E6/xPXqoiE3hEIKIOyaBI0/yJfV/X+rABK5JpbXTD3/oFA8IeytF0HVt3NUwvQJbRQEgdbyB2HIJgnpX4QEBDAKQnQdjSFkEwXKbRCgelVDAVQihVDSE6Hg/BBC8FMA1JWTGpYtJfx6C/RYmBMGX2AVg8BIAS5qQRDAHoppDxoE3HAAy7CyL5noHMDWFpoY+D4cIxCwVaCOFoEPEoddcx4loB0YRmAeCbG+vqII0cph0AeHYIkQR3SKyyvTEAeJ1jEweGgqoQjzGWPvMQB4GR2JgCqKIPu/gsZGhse4rIKsmDeK7L41xHcPFomGB2XxtiAknCiVwUJMZwlZVOMCW4uAkCzjCf40Q6h3oaiCCEFgqBpwSI9o46xOSIknCSlcLIKjbReDQHmIx6UTGYDyUlAAUvoy8RJdTGN1J0kWTBKnONiUItJ4yXHJNyZEkAwSkluJqWkzeWBMkfHDrMlZqS+qNjBA8K2Cx0BBDzIkhAvg/F2LRElO0hYhK2gBBgCIQzTF5LGVxJx1y4nTK+VUuZqyEkQBif4qZQT2QhMuT8qZ71vBoFjESCgDxWYID4O04ZqTPlWOcdUrFFj/kTLBQspZ0K8UfPgLkWaelCiPMmQs3A4doTThHDChZYJ6SMpHMysEhQ2W1IgaCLg+jnx9jeSMgVIBEINN1A8AAcr2Lw/JxVZXDDM+l8SCU4p2SkilpKrkarSeckFZLAX4twAgBABBlm6tuUwbp7R2QgXwp9ORZzonQsNUlW+oQ8wYHVLfBA2J7xBHVcS6AfcZnkq6MC0FNyI1MA6VlLxkK42/IhT401uyun2rfmgfRJDtRCNAEmilYb41/O1dGzV+r+VGo9Qa8NaSLVWrTeCxZqas22slTaRxIFekkWTBi95QwtXfOrWqwldaM1QqudWtZttYRMpQCyvlhrY1dvmZKq2lgeARA7NCB40d3CDOHRKvuHL1Qnq4pwW4jxKCyIWeW9NY6AXZoWcatt7LF1ct9Ku6dzdFYbKySuPl86mAtutZuoFCYrUQA5Gg1lXqGZQIwJqbUKBtFnuTdi7567m6LuvYhu9gomLtqjWavVnbG0Vo3TRl96zNmgZ1Vuo1cGEPbOQ1K6EboHiBuGgUJupbR2XoeER299xSOPs1c+8jU7wOwYIPBkqnGm1MEYyB7ZCnP2eqbUlK2FBgIPEfFjaEqjQCyZja+3FlGP0Nv5X3HTc7bOavMExljqy6kbAyCBKU6MwBhBVaIcxonxOzUkw+l9lmZPyZc2k2tCmNNbNZdp9jKmkN6aYDYZSdxjMUC7D5qW2Gc1mgRJ4IUGQj35fzcWkAwmYvavwxR99NbqMAacwB0Tv6eUZdox2zNzmWv5KYFcR1bRfOfgGYF4rdqQDPkDOqKkX5jRBe/fSMLJHItyarXF3D1j8MJd24BtAwHktgbi0lT0+ZLBoY1JYTYeQhOYrLVOprsWhtMDgFSsRI46VqZAN1ldvKAOkCEsyU7zH509JnPYB4nosg1dWwmgj62CzEYi2Rp9r3/vNe7fWi5g28d0c60BpjWmjvSmU4htd/3DtDaSnK9MhzLxRi8Pu0N72ifWYA/V/HJrCeseGGl6nHn8W1q43aewn44eoFZBzxrmWQA2mhsioqSBsTowQPLvD4a+5fbkT92lwkNV90B/+/D9W+6g8Vm0CH5OWuRs54LxTVPVMVqSpw5xMFMPmbq890d0WF2o5veF+9mOGvjqO+L/7SXIcXaYFbFpN3QKsmIgQV5M3JXSoyPo9av90CfxLf75Hge9s2Y+wmezB22upaUxx3rL7o/u4mruckwlzyYfJEj9WG2MfScrTrvruPndm+B/h634Oycpfj9SGgnhZoPEAsfEItXedl9Fy9hX8aU0DY3yStr+GOtcauG0GrDwnBQlqpa+q3Pq+7645w/Q5W8RodNJQXAFqSLa/27Tg/iuABaMYeY3gFA/QOECIWQEQ2Yr83+RKfWTevyHuhI+48+mo6YW0pe/Ws6daSULOmwBsrQcOoIEALS+WsBAG+u1K4cf2zeSuXgiAwk+EuoGG5Bd+2BXGkCTEcO0IEc6UmBCBsKEC6MjwfmU2Tc/Bf+tB0q4QoIaGhir8RWoAveYe/e6+CmmBE+tuU+529O9qCA5yDw+EQq9gekSOw2kob8QoIEjMPAVh7qBO/KDi2O8aM8khcS4YdO3afc9WSC3O1aIWpOmmDe7aHWUOTAdoPAYA30fGly0INQhefuI6kqfEbY98kASOjm9mYRIAl4+BZ+TB6evoCIN+lu6+b2O2FeR+MegRZ2OB7k107wPgoEYI1AKIWufBzhL6bmIGe+rW9+emSU6iLAVAT2SRUgPQeI9IcAAUpAHoyMZR4a/AHsX2ziaAPYRIpmeSExTuNSig4YyIpY9I6iwYM6X6EavhnhrGo8c8pSH8QiHsse9u3aGIVR2+PQKxDw+ivgx8qi+x32NKNBcSvho+wRImP6y65uixxO86pulqUGAuNSpuM4PgAcHskGZxQeV6aOEmKhcSHslO9eNO8ayxFonxIE5gJQGI0xsUsxaGGq5imhdu0+LWvhBJ6WOhXOHx+im8CyXYwMniTAyhUmcSeuFQhY+K3R2SLm5iuAGQaGQkrc6mi61JGwtJ7KNRzGJuSUlQ1QmieIvul4diBAfEZAQkhi9g60w83MHshp1Q54XYtA5pok/ENk08+MRp9pjpCI9gYECArsJwvhtpeQ5pusxo0IVQ60BQqopy3MgZHpWMXp+gPpOc6x9gjO1A7EeScZdpCZ5ppoUwTY/A5i3oaANoVkcATBhgmc0Aig2ZeQJp1u14OQeQ0IfEaU2C7p1Q98aA+URIZZH+HMjESZAg6sQZBA/S9g3xCAPpIc1QikLAGowULSKsNpRpuE3ACA+cmwkZBA0Z6gK5nZeQkZ9gVIFEpAvSvBexh5xpqpZp3pNg6YuAQMf4hZ4YY5DZd5SZUibeaMAwikJkNQaIfcY5JcyI3ADIr8bQd2CAHwQo2MKsdZBAoFhmGAEF7QNs1Ao2YA2ISAee/IAc15yF4FkFd2+WdorInA0QtZhFhYKFaFbQiEiESoNZiFRFqFJF2oHwyASFVpygNFYF7F7Q+E/qBALgCFECQkZZicAgb5Rpno+E+EyEKAxANh8MBAXsyqmqUogYjM+gjK0QoYTAcq7w2op42Eb+AUb+XgaU/AwFRpFlsU4c0c2Q4cjsKAn+K+RWo59lIIjlI4blHlksGAS+ogtlDMvlGw14oV5iY5/Ms0I4vZ+gl4VAv5/Qp5yArgNZGI75r8is/IlYpFis6ZfEPsEAusQi/Asl1QhVaA+VxAKoaoz5RA3xXgoVVV9ZuVtVlqxANVJVHM5VAgaSOVm8dVvVCI/VtAvIiAnevCVmw1eV3VDVBsgar4vxvhVsuA+QNVQ59gAgq51VnVdVS1CIp4qA5QtAJClo1QKsPQ81XVlYx1+g6ZXesZ15p1FWKJb+lEqidldpMweIn1IcbQnQc1RpdgBArIikKAtADlGwAgiFE5U5M5lEc5rYBARh6CwW2VRpH5aA5pieaAWoMYjgZVCE3M3lc59oO18N15uN5pi5WMEAVs0xrYJQPM158lileIPVeYxpnVL1/At1Rp3ZiVJmuQ/wGNAIMl15sN7UhQoZ2IvsYAuAYcI4XQMVPlAU4c3IhQ5QGQRU6Y5s+1eQst4ct8KNRs1U9YBAp4URGABMvgiVjOnooIoN1Qvp2MF+OpeQmS5s7NORa5Ocm5Bwpoa4B5AdB1I1i1tIBsX1wEBA+UoISRgttNh10d0ZCIcd1Qidm8IgOtetBlQtkdC1lYz4vCqAqFM4VFQ1ONadlY5EeA+0XcNt3pNcGIusH+7wGAuUowbNiFNVo1nVfVIg5VJCM1NlNdxd91PVnVp4vABASNI5qdUdlYdo2IJcBApoDorIyaiFcdbQz5UY0IJQfFEdeQiNlqyN8d85fNPJNZGt7tEVctW54cS2Q4JQe9T9r9BcI4V2HwmAVAgSZ9m9X9I4L9v9MOAD6lutL+QDY5ptI4LoCId6AgD9eQnp5pt8/iKA+Z/qdsRd6DuZ3pTZyALZKAyEvB7VBAx53oRIvxk9HVK9xAOdpiKAGl7RVDA93VLDmAbDfICAIN3My9JdzDXgudfDIICAigo6d1R1MdCIDduAw9pNNl/dddxAz1pAd9nQiFz4vY4cNVktXAIVvgCwKs2N1Vt5eN3pLtmQi81pwj09j1RNJkKjKsqgjjcjGd+gLjJNusMwLqBYj8aDBAIt41FlvK0IDdZCM0Mjwt5IiVlpbNFNhDDp9N/IisqZuUqAWGnQDDoltAxk9gaM+gEA+ELR94cYcTOZaT3pDNmT3p0qkFtMMtoDhQBtRIjsK8ltwDdN3p54NVe1nj3VZdfsGQpoN2mVKdvT6jj15tWiNNMzTDj4fgDNr4IgnobQO50Z2swzpdfg0q304d8DQNqVRjoVn931LoHo7ZHjwDCDhQ5opAmMpc/pYV9zbT4DhQW5rc+TDzXzAV3NQVaIfzbTikoOr83g9wqDezxAij6ZXdtDXM/tsj3Va9IorIc9RIjM1JNlKTt9IjNV/MCKYO/8KLPl31po0M1Qp5mQqj15F905WdR5aNPdvgpjMLHzWtI4zlsYI4p42Mu10A+LDzvL4cAr0I9g98its1wrrT3L7TyArI/S3xXYJ9IrbT54WS/QKrWMaAyEKsGrCrYrI4odatcrXLflhQyEDp3iCpoylrP91rMcpr7oBQgTmV+LYTfZSAA5IgNhnLsV3NdgjgSApAgalYIQRA2z0I7DsC8rVrCtStKt4cgTBQPTJzCrD5KA9g3FiEFo7LeDaAHkoVv1JtbT2bubMw+bVYw0MMJbjO8bjrctttNQyE5QhrCbTrrb+rdACA98mStCNZRrVrV2tAHTRtXbctpoTgAAmqeBm5rVa5W3mwW3W/oGzWWyA1m3iFW6E9xZRYu4/Qq4C8pUFVdqIMbaEwk+NYfdGGMO82Od6/oC6vxHkLY3PMk9eZrIUNxb2iel6EgG0LbQBX3W9f9SAfoFg1UCgD6mlFe0pXC2I+UJABG5aFQNEFe5zYh6pbzR+ywCfRiEwSvP0NBQMOHFbCCkJAQA9mlBiLyG5TVvzAiByNmInmmQW1BA48A8efvUM8A2xfRb+fIlS9wPDo/FQ4J5BeDTvXkpJ7RcRe0IxdyFvUEzABY3kFJ0p0xZ6KQ0VkQsAz+3m5wNGSXN4G8yE8+1JeXOTTLS8zUFS7rWGwi0Vnc3dZR1MBkBI5pW57XZvB5wWLG/w8Za57Cys74O+Pe3bWhCcFu1w/XfyLgC5xgKp+m9zFQ/vbyFGIFycSALQ5YNQBddqNCJYIZmbTGMFLcMl/MXl8gQ0bQCzvZ2gPfNMa6AQNV0XBJT7IV0fAveNS15V+11al3TV/l/V6aF2FEQN21x17jAy0mUjUVF+DMIXWF77BXS6A/P/HN0syI6MxXRMznC0ljLszx/aPmdOVRRpwS9PUS3+KCLwmYtd0ZzMGxWZ/4u4xJdYzIlx+oA

**Comment by HCPTangHY** [comment]
加了一条修复旧版赋值bug的代码，请等待新版更新
