### ISSUE TITLE
人物界面介绍他是你的某人时出现爆红错误

### ISSUE THREAD

**Issue by yawnzzn777** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#6]
版本：[0.5.3c-chs-9981-2]
![Screenshot_2024-09-11-23-50-37-237_com courseoftemptation app](https://github.com/user-attachments/assets/44216366-5de8-4005-8ed6-3330ebf9d1ae)
存档码：
N4IglgJiBcIMYHsCuAnAzgUwLQIGZYBcMBbABwIEMCwEA7EAGhDUqJlDFogwA8YAWJpgxRoABgB0AdikBWAGwBmMbICcARlX8N8ptwA2lGAG1Q1AvowwQABRR4MaNAhQAVCvoDWAIQCeVpgA3ChQwCgAjSzR2EGIKUjQwAC8raGN5MTEGZTEAXSZSFAwMWkQkWiIUSgBzaLSQDECSgkYQWgRwlBB8kAgKXxgAJizYugIACwEmceQu6HVZJmJOJDZoVSZ/EKGxTSZqimIRfoEADn3DjC259QK4WkvrAGkwAgJfAAIZVtJ7sDhPA8jtZvndqiVuHMQAQUBRaGhwVwMCgPrgSB4AiBfhRwTB1OcsXA4gArFwwWhIfT6O5ldCOEwgADiJWRHg+NjQvjgM30CGqAyYAEkKvYPgQEOzOdyELz+a0bDNxdVYaRxp9Ba1mbRWfoPgBhcYkMAsFADHqk8J1YwgADKSGIywIHwAsiFPBgWkwAIpIf6eMAYbyocFdHq/Yh0K5DbT8NR3NCkDBwAN1EDje1wn5wK5JmVk2CRJCY37jChgFCIXlQtDlTBOhDETrF7ll9DvSzWXkITAfOEQD4AdwogQFhNL5cstGqE2sywgWHCFABH0n08m8f9pTzUNwraznDg+k4VBo8IZrgQnwAohV04kKCxWgAZDAD/tXnjjMDhV6n42epkZW4WgPhtGYB2RZFWj1e00H0VZWgAEQbY8KiQlCHgqD4ADVv0xAAxFwhxQKAmDsZB30/b9fzof9Wncd00HZE8SmzeiQnBAC9QoVYaCQJiPy/H9qFox8mGwy8MFQeUZV8Q4XGQaImAAdRmIpuiYA8jweET4XKXkAREGIL2vW9+LCR9oFACAikuUQYSLABfJgXzfD5BOo3S6Ks3pbKOeyUCcphGSAkpQPAyC5msvyjOgByMGckAYOIOCEJ8myMDsmB4sSgAJVsPlcUJqhDGIMqyuLAoSphCJQYjRGizL/OyqrEuQ5ZMJadKYoCoKQHa1CnVw8JUkaiqcrI+wkEooSaNobyxuayq+oYxxmOoVjRt8prYompKeJE/j3Ko4S/0sxbdtaph3BQTiyp6lq+ok/xpO6nbeuq2xZPkqa6guj7EtUlwtvKpacsS340H9Kk/qS0tQjQOI8UyEZlLAKlSAQCCbhRpgPNO0TiBgWQFnEyTUGNInoEGQZFCYG1eCQNknnaAdLAgXFoFjAlEONThZt0mB5FUHmMLhNj5lx20kHCZYnFPGBFEGDYQHyrgBDEQQQAAeVhfQBEGXQQGwnFj31+YRaYABBB5zaVkYbBZGETyaIZVCkIUKgwKkkwIJnzfUKWbT9iBfE4apkcyJhEPF8PI4dtVEjgDx47IxU+RVNVU+NyAMAlRlDjjyWo5AK2qn/f5s4LkiSiLwPMghuAWCoWGcVSfFpgwMBqnGLrhcGAp4LIbUnB2LXiH4w9UnkdQjabB8nUSFJs8TeamKX9upYfdfkk3hu7m1ERYcIhBRHkfgjYAJUcLqpGUaRTnUQZFhAa/9AoHgTzoGBTjEFWrbeM0BWxcRjeHfhASEMBVDuwkC/XKvhqgBm1DAKQpxZASHdjTLB2DBhaz1A2TGNZ1IgKYG/TKmAoG4IkKcVQYh5DP2tr9FO0AlCKAkBfR+gx1D8FjLQsQBIbQnjQLuOAgtxBkTLPQcRqt7TozCGIkYiFAq0HdLQEedQxCNzUrQAY0jMA8COBGU0MQY7LDoB8ZSHhzagH9E4WKdMQAuAOIjD4iCmhSIcU4h8xAPhFGzGAJoogB4gEiFjC0riAklEVkwUJA5wl+K7oEvE0w+zhLcVE+YKSuDxKTIk2KtxoSvFwEgZcCTImiHUIlGweoYhxBYKgRcYiPaONut43xuTyl4kSk8EoOiXQhDQKWKkMRbGYAqYlAAUuYq8VJjQjONGMoWTAvEuPSVIgpKyfFlKSZkkJvI4kdHaf4nZBTt5YGKQCcORy8njOjr4d+IErb+HQDEUs2TDlrK6UwV0FYjrOghBgJI8y7EVOWa01ZkT1lgucVsjpJyskQDSZC5JeywkfORfMKpCNkxUgoB8FmCA+A+VGfk6FbTtmkpaTCiJ7iUWxJyccylcByjzW0tUI6nzdm4HDsiRcU4aUZNObbVEPKUB8uqAK9ZiVvCwi4OYl8I5gWLMxdHXpxoPgADlhwhHsEq2KWtNmSpRYailoLUUHPCEa3ZbzEWHNNSi3ACAEAEAZTcr5IAJn9F5CBfC+hfBqNeak9FtKVWv3iKWb2HxL4IGJA+GIhrOXBJNXC2KwSbVIpDcEklQSYn7IzYK3NaLLX2tDZ6ngzgQL4MNFImxCzKUJoxRs8FsLGVmvpcGgtaYg2Ws5QUx1zr81QvNa6zpobnReJAlMkimZiV1tEAa5t1zR0Lupb2wtFql3wpAHCNk3Kpy8rhBKtdXb3nFpTbc0ulgeBJD7MiD4MdAhzNnSCoYTAd26kfbdTgrxPiUFUcaxdx7k2tpRemjtQ730iv3WKw9VrTlOHOSUzcEqS19qdS6u157QPOogHyRB/Le2JRtOAjA+pDQoGMc+5VSbAONrfcKz9+Gf1igoP+3ZwG3W7PbT2ujJ7bU8ZDfBtAiHLn8tQ9MHDeGrmEdVaEZc0aRpVFhtmqY26GPliY+8FjbGm2rt4xx0dBTFS4ZKtJ3jZyLnIc3ZSsDAnBWJSthQYCHwnxY2RLo0ADbM1kpceJvjg7X3+cwyB3Z5hLPWYvU8Q4RQQIKnRkeBIerRAOMg4x79Wm/2dq81lxdfnuMRZRRZpDVy/PGakwRxtgM5JvBcxQAcMWJa1pfaGwR+hgjiiKPeurFaksAb04JnzLbOMFPy8e2zcH6O7tFeKibw7gvDe6V6/17IvyzMS1R/JiUXyRl1Iyb8lpeu7NSxp9Lv7WM5epX57LQ78t+aK6JlDWHQ3eDLJYUjepLBHAqMpudfW2lAdy09gpzK1FyKnBy3je6QwzePaQfinIRNWdQ5MpcngPjeBKD1jbOa1NsjS/NDL52h3Xb+75oHCKR1bvG8e+7SPydpkk6ZirA25tnpC5UpgGqZRwncgmEIN742A/Z4N2bKnrXdoK9axn+HHvC9Z3BxKrpPBfnR6gbkgv+v2e+ejPFRUkDEniwgDX/2MXBJB6y8OEPvMgChwe5nnaxfBLh04XwiOStPZo5d+nZWmdHsq/TQ4+pUCUaa8qldJuWfHa/QTs7OmRd5bzeBwrCHLPu/Zw5wZb3QLcmIgQIF2P3WIUguYmwVBKhY9D6mkXAOvdy+p7x273vpdmZZ6N/3thQilEcExC8FH6QF5YUEE7MftMXYj2Psncvbcwft0O53CPU9iaB4lPbCBgjzQ+CFU+cQa0gDF7p8l9OSfU3XZTylbeWf18E903wFaPgAFUkR1SdQ1Kl4+buJ7s1KgPbWqDA1ApQLgI6iRMbhCq3p/grkwAAFpJjwxhDjA4QYi0BJBFjvygE+LHoX5a7SyzLr76gyhbTH4jYQEyYgBXiIw6h9Do6wgQCDJ1boGzbm5g7spMSkE/KIBMT4TGjkYMGYEkHt5gLnbo7IgRw+REGn5J7PbxafBxZrawziHy6kFF6JCwikaWK4qNYgD47MaZbE5C7DbV68bz6u6L6y4LZMBTJvIfD4SyqeDaSHYc62AfziggQMw8AuGBqnpWqeK0Yhpzz8EhpayN4hZZq/bQAvwGY7IpYp7Faz6gYS7I7fIfxgARhRodDIgEAV575hGOHcQ9jXyQCHZpoJHL54xHDoDmJcF54hgeCv6O6GEs6RE2YS404xEPaQEgAvjUDJh4qCIVBhDVBG5iG+GdphZIaS7EFFoK6JT6LNyZGHZSAjAuBshwB+SkABjIwNEZL8DNLMo+JoBDhUhuYVJLH6GjqKBazJw1hsj6LRgSFf5DAvzBHDbjwLwNJfxSLNK05p6cYEhX4ZLDBMB7EfDmLhCny6KXEsrMFW4ZIvzT4w4YpayQbwmwacpazjaobBL9oYZs6cZYlLhhABzNLYkBZHbqbR46FE4oISYEAmYy5Wq7H2ggkgTmB1AEirFNTrGkacoOLGFu5L4hYvw+70l+bAnmLbwooDhqRV5aHD6UlsZm4IDIjZhmpjGlJPYOK4BFCkb8TtyTa6gcmHBcnJ7CamFWqDCJSNDNCGIuAeZkHuIEDcRkD8TqGeCl6jxczNJXgOkXgDi0CumCQ8SWSzx4w+lYz+keCeBgRr7twvzenNCunayWjIhNCl5VDagvJcxxlhl+muk2i5yHGeBc7dH5LZnNC+kRleA2jLAdhcwOJBhoDOjmRwBcGGBZzQCKBlkVBOnO43hlBewoDcRdSKAqzxkVDXxoD5RUhNlAHszuBeACBGxjkEAzKeBgkIBRkhzNA2DdiOmBSDKKxekOm4TcAIAFxHBpkEAZnqCHmhnbluiMhTSkBTKiEXF3ndlGkumRnKQyi4CqT/i1k8LvmOmfloCulKLd5owTA7mGTzHzDBLLllzJzcA2Dvy+AfYIAAjijYyKxdkEBIVOYYCoX9A2zUBRZgDEhICl4wgygoqIUViEXEXoXvwDiujcicCpCdnAUEUoVoWISIQagdl4U8VEVoUGhJieDID4UenKDcUMW8X9D4TewED36kC4VMANlNlJwCBazLneD4T4TIQoDEBuEGhUDCg0UooKiRgMz6DcqpD8AEgar/CGiuDYTBx+TBwhBdT8AIUOkeVNThwxylDhyOwoDAE74SxLn+UwiBVThhURXiwYBb7zrBIBWHA3jzoOLLm8zzRThTn6BXhUBQXjCPnIBqUdkEjLkfbbz2ANg1VODFncQ+wQDaxSJAX2nNANVoB1XEBag6j/lEBgkhDzq6UOndW9XdXNXsxtUCAFLVXvxOCTWLVoDTUiBtXCiIB96iKBYLW1VOp9Ush6zRpvgQkvxWy4CVDdXzmeBnDAUTUHX9V6yuCoDtC0D4IOjNCKwjB7VLWPVHUeDFn96xjAUvUdaEnBzTS6J+XlmrAuAQ0hy+CDC7UOmWIEDcg7koC0DpVUwg2dUVCrnrmbnTTbm7k2FILJZVXjWgWulWxODiWGStVpQXzAVpmeA3UCB4U9lfleB6j2BvhWyrHdh1B416UGVGXEBmWOkrXA0/UOkTkFWublDgjk0Qg6XAU43hxJnEi+xgC4BhxThDDZUxV+ThyCjVDtBFBFQyjmxHnNCa1TiXwk0Gw1TlgsCuApEYD4wFVc4yoUAo320RQoCP5WkVDFLmyi3Hm5xnmXA2h5i3n43S37UNhPUeCQ3AQED5SwjNb8By1dUrW9Wp36Dp3NBZ3bwiDm2W0OV53dkF0HUviiKoBEVLicXzXjV10NjkS4DcRIA9wEA3V1wEjaxAH/AYC5SzAi1U353J2S0rVrWtXvUuB+I+Vt3T1/X1UrWuC8AEBE2Ln3Ud3ECujEhlwEA2jujo2GhBJ4Xp2+D/kJjIh1CyWJ2E1OrE0Z07ksDdWKzG322xWFxTjnnhx7YoD6B1DX1/0dTVCANTgvYAiYBUDRKJ0O1QP/3VCwOeDwMECV3AyIPLnIM+geA/oCA/0VAVmumXyRIoDVnex2w1393hkBlbjlCVDISiFjX3koA+CUh+pzX70z1l12IoAWW6pcx8Pr3EACOYBCMigIDI2iOJ0PUNiSPIjCMICKCqa/U9X/UZkeBd3z3azM1c0H1A2kASnUx4UvjDjhzdWq1cApXhD+CKxT0fnOlgWRkyrFDLxczONJ3iNF0M3uhM3Dmjnt0z3+OGiM0GMEC+rlhdTqAkMEAK1WIeWHrIjkSEJzQaPy2OAFXuki3RXlkMORl83C2Fm5TB7Q2r0VCP4GSeBoz6AQD4RwiUCJDA2g1FO832BOCFlF5oVDAw0VDIPW1UiOxrwu0KM02RkXhf2eliNaMNgN1+xFDEbFAVW51zOF0A36BO1GKc0bP10RAlNvgiB+CXkZkaz7MLMRBF4RgJ14OI0lW2PzrgNQ0+gBjBMa0QPhx2ikCYzlyuxcwDOn1fMAOoPnntxVPAum2guQMJUuCRUQufPQvVA7lw7vyhDvDEOXPEBd3Fmj1Bj6CcyR1r3zOH0UDEgchcjjBb1UgMwck+UFO10z3dW8xoDMryzfxZmfNQ35mTgECPnFA+V4Uv0bkl0VAf2Z0dAONYtIMgvVDBXJhTiuDYy3WD6yvIsKvhzKvIieDXw607Vqv3PIsXglLjAzJgkDiP2MtQtxXVAmvcjmtYxoDISKzWvIOatThx2G2Gsm22vIR+mhK6lLLqt+uxyev+hVAxMVXWtJPTlICzkiBuEys5XwuWLuhICkDRoNhxBEBnMqMyPUkhuoPa26363hwxNVDjNGu2s/mcNSWIT2jhAjQwyuSpVIs1suCSWrANuNjNugOttc6FvVuoMe2ZHITtCuvtsjuvDOt0AIDXzFIUIdlutysva0DDO21TuQM2j34ACargVbvrqDtbXbBAPbTbNDItQLyDJ7Ul0avEyCgLW7oVyIiVXeL2ogdt45OTVid9iYcwvlwFsb+gvqPEFQHjC8+TwFasgxqw46j6gYSAvgHtsFIteFYN8NHgFDTQKAl8CD0AX7Z78LaZcICAkAWbDoVAqQhH+lhl8LplpYBAEHLAj9BIXBa84wGFEw4cVsiK/EBAX2XUBIwoYVFavMHgfIRYdNRZjbUEszidbNN9AghHIlTFUF6i+Z3AGOcT7DFQqnaFaN3I+Sun+F8lol/Q/FgoZ9sTP8clyF5nvgln3gyAXe/T0Hh69bnAGZZcoQAL/ACTwHWllcXMbrfzmR+ZFtGbeLEsITJLvHywRQ0jll6wcz8X5Y+bNFzlMX2LT4EQH4/7ntaE8F2LuLzqo91nlbXMJnN9woCY6XdxIABLlg1A71hoyIlgTm4c18qxvoBA0Xm8Gl3DHonA5BYXaA3XgUrw/XmxjXQ3LXJ8O9ViE3vX03ksg3PsLXNoA4KRy3U3ZXEsgcwFIr7NoQ4Qqw1dOXvsTdPoN8wCh3CjB9izTdxGucgyWMFzCnbo1ZG5nFPji

**Comment by HCPTangHY** [comment]
已修
