### ISSUE TITLE
v0.5.3e-chs-1.0.1 食用庫存零食及啦啦隊遭遇爆紅

### ISSUE THREAD

**Issue by acain000** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#7]
1.點入側欄庫存>吃零食介面後會爆紅並無法吃零食
2.加入啦啦隊社團後 在橄欖球勝利後的遭遇會爆紅
![Screenshot_20240916_181051_Course of Temptation](https://github.com/user-attachments/assets/80426623-f06a-4c5b-823d-759bc2566f45)
![Screenshot_20240916_181112_Course of Temptation](https://github.com/user-attachments/assets/998b0af7-5db9-4909-ab89-9860f1f51406)
![Screenshot_20240916_181322_Course of Temptation](https://github.com/user-attachments/assets/5e673580-af56-47e9-b7c4-9e37a8b2a1fb)

**Comment by HCPTangHY** [comment]
已修复
