### ISSUE TITLE
NPC介绍页提示错误（0.5.4d-chs-1.0.0）

### ISSUE THREAD

**Issue by randomname333** [BlackTeaPie/Course-of-Temptation-Chinese-Localization#9]
个别NPC介绍页出现大量错误提醒，无法显示外貌描写、沟通以及自定义。（图2）
这部分NPC在剧情中也会提醒错误。（如图1、图4）
恢复成英文原版错误提醒则消失。
有部分未汉化，但问题不大（图5）
大佬辛苦了……
游戏文件版本：CoT-ModLoader-v0.5.4d-v2.20.0
游戏汉化版本：ModI18N-0.5.4d-chs-1.0.0.mod

**截图**
请上传报错页面的截图，截图需要截完整页面，包括侧边栏打开的顶部版本号
![01](https://github.com/user-attachments/assets/59b85fc4-c5e3-444d-9355-f179c9a0e9eb)
![02](https://github.com/user-attachments/assets/80fcb253-c968-4324-9240-9f647b341c26)
![04](https://github.com/user-attachments/assets/1838122e-f233-4b29-8835-0ec80a8eee82)
![05](https://github.com/user-attachments/assets/3cfcd0de-52d4-4bc2-b4eb-38c8c58ea259)

**存档/存档码**
[NPC介绍页提示错误.zip](https://github.com/user-attachments/files/17309434/NPC.zip)

**Comment by HCPTangHY** [comment]
已修复
